// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7lNiDfkCLCbxXr9eHRyIHk7HiTSR6kM',
    appId: '1:538777458805:web:bcf819cb0232d886e4c03c',
    messagingSenderId: '538777458805',
    projectId: 'flutter-instagram-f7533',
    authDomain: 'flutter-instagram-f7533.firebaseapp.com',
    databaseURL: 'https://flutter-instagram-f7533-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-instagram-f7533.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEv1K6VW3iBVg9D-u6jzqw108TjQdgvhg',
    appId: '1:538777458805:android:6bed3020a81f8b3ee4c03c',
    messagingSenderId: '538777458805',
    projectId: 'flutter-instagram-f7533',
    databaseURL: 'https://flutter-instagram-f7533-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-instagram-f7533.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGPv-B9axMzTetcuXrs3fokTGYPxQxQis',
    appId: '1:538777458805:ios:0814720a7316f261e4c03c',
    messagingSenderId: '538777458805',
    projectId: 'flutter-instagram-f7533',
    databaseURL: 'https://flutter-instagram-f7533-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-instagram-f7533.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGPv-B9axMzTetcuXrs3fokTGYPxQxQis',
    appId: '1:538777458805:ios:43613ef05b6acd9ee4c03c',
    messagingSenderId: '538777458805',
    projectId: 'flutter-instagram-f7533',
    databaseURL: 'https://flutter-instagram-f7533-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-instagram-f7533.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
